import { describe, expect, it } from 'vitest';
import { classifySystemWrapper } from './systemWrappers';

// Formas REALES, copiadas de transcripciones del CLI 2.1.283 (sangria incluida).
const RENAME = '<command-name>/rename</command-name>\n            <command-message>rename</command-message>\n            <command-args>REVISION-MAGE</command-args>';
const EFFORT = '<command-name>/effort</command-name>\n            <command-message>effort</command-message>\n            <command-args></command-args>';
const SCHEDULED =
  '<scheduled-task name="say-hello" file="C:\\Users\\u\\.claude\\scheduled-tasks\\say-hello\\SKILL.md">\nThis is an automated run of a scheduled task.\n\nSay .\n</scheduled-task>';

describe('classifySystemWrapper', () => {
  it('classifySystemWrapper_textoNormal_plain', () => {
    expect(classifySystemWrapper('hola, revisa esto')).toEqual({ kind: 'plain' });
  });

  it('classifySystemWrapper_vacio_plain', () => {
    expect(classifySystemWrapper('')).toEqual({ kind: 'plain' });
  });

  it('classifySystemWrapper_commandName_devuelveComandoYArgs', () => {
    expect(classifySystemWrapper(RENAME)).toEqual({ kind: 'command', command: '/rename REVISION-MAGE' });
  });

  it('classifySystemWrapper_commandSinArgs_soloElComando', () => {
    expect(classifySystemWrapper(EFFORT)).toEqual({ kind: 'command', command: '/effort' });
  });

  it('classifySystemWrapper_commandMessageDelante_igualmenteComando', () => {
    const text = '<command-message>statusline</command-message>\n<command-name>/statusline</command-name>';
    expect(classifySystemWrapper(text)).toEqual({ kind: 'command', command: '/statusline' });
  });

  it('classifySystemWrapper_commandNameSinCerrar_plain', () => {
    expect(classifySystemWrapper('<command-name>/rename')).toEqual({ kind: 'plain' });
  });

  it('classifySystemWrapper_stdout_devuelveLaSalida', () => {
    const text = '<local-command-stdout>Session renamed to: X</local-command-stdout>';
    expect(classifySystemWrapper(text)).toEqual({ kind: 'command-output', output: 'Session renamed to: X' });
  });

  it('classifySystemWrapper_stdoutVacio_salidaVacia', () => {
    expect(classifySystemWrapper('<local-command-stdout></local-command-stdout>')).toEqual({ kind: 'command-output', output: '' });
  });

  it('classifySystemWrapper_caveat_caveat', () => {
    const text = '<local-command-caveat>Caveat: The messages below were generated by the user…</local-command-caveat>';
    expect(classifySystemWrapper(text)).toEqual({ kind: 'caveat' });
  });

  it('classifySystemWrapper_systemReminder_reminder', () => {
    expect(classifySystemWrapper('<system-reminder>\ncontexto\n</system-reminder>')).toEqual({ kind: 'reminder' });
  });

  it('classifySystemWrapper_reminderSinCerrar_plain', () => {
    expect(classifySystemWrapper('<system-reminder>\ncontexto')).toEqual({ kind: 'plain' });
  });

  it('classifySystemWrapper_scheduledTask_usaNombreYCuerpo', () => {
    const result = classifySystemWrapper(SCHEDULED);

    expect(result).toMatchObject({ kind: 'scheduled-task', name: 'say-hello' });
    expect(result.kind === 'scheduled-task' ? result.body : '').toContain('Say .');
  });

  it('classifySystemWrapper_scheduledTaskSinCerrar_plain', () => {
    expect(classifySystemWrapper('<scheduled-task name="x">\ncuerpo')).toEqual({ kind: 'plain' });
  });

  it('classifySystemWrapper_taskNotification_usaElResumen', () => {
    const text = '<task-notification>\n<task-id>k1</task-id>\n<status>failed</status>\n<summary>MCP task k1 failed.</summary>\n</task-notification>';
    expect(classifySystemWrapper(text)).toEqual({
      kind: 'task-notification',
      summary: 'MCP task k1 failed.',
      toolUseId: null,
      status: 'failed',
      tokens: null,
      toolUses: null,
      durationMs: null,
    });
  });

  it('parseTaskNotification_textoMedido_extraeToolUseIdStatusUsage', () => {
    // Texto real del CLI 2.1.284 (spike --subagent-bg), con la ruta del output recortada.
    const text =
      '<task-notification>\n<task-id>ab255314fd2da405f</task-id>\n<tool-use-id>toolu_01M2</tool-use-id>\n' +
      '<output-file>C:\\tmp\\ab25.output</output-file>\n<status>completed</status>\n' +
      '<summary>Agent "spike A" finished</summary>\n<note>A task-notification fires each time…</note>\n<result>A</result>\n' +
      '<usage><subagent_tokens>19906</subagent_tokens><tool_uses>0</tool_uses><duration_ms>1422</duration_ms></usage>\n</task-notification>';
    expect(classifySystemWrapper(text)).toEqual({
      kind: 'task-notification',
      summary: 'Agent "spike A" finished',
      toolUseId: 'toolu_01M2',
      status: 'completed',
      tokens: 19906,
      toolUses: 0,
      durationMs: 1422,
    });
  });

  it('classifySystemWrapper_etiquetaDesconocida_plain', () => {
    // El usuario tambien puede escribir XML: lo que no se reconoce se pinta tal cual.
    expect(classifySystemWrapper('<pasted_content id="d1">\ntexto\n</pasted_content>')).toEqual({ kind: 'plain' });
  });
});
